### PR TITLE
Fix sample example - update compaction configuration

### LINKED ISSUE #65: Sample example java program fails with Accumulo-2.1.x
When run against the current Accumulo-2.1.0-SNAPSHOT, the java sample.SampleExample class fails with the following exception:

`Exception in thread "main" org.apache.accumulo.core.client.AccumuloException: TabletServer could not load CompactionStrategy class org.apache.accumulo.tserver.compaction.strategies.ConfigurableCompactionStrategy
        at org.apache.accumulo.core.clientImpl.TableOperationsImpl.ensureStrategyCanLoad(TableOperationsImpl.java:900)
        at org.apache.accumulo.core.clientImpl.TableOperationsImpl.compact(TableOperationsImpl.java:850)
        at org.apache.accumulo.examples.sample.SampleExample.main(SampleExample.java:105)`

The sample example works as expected if run step by step per directions. This error occurs only when executing the automated java program via the command:

`./bin/runex sample.SampleExample`

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #65 

This PR moves from the deprecated CompactionStategyConfig to the new CompactionConfig to setup the compations for this example. 

I'm not certain that this is behaving how we are expecting it to, however the errors are not present and the output looks as expected.

### CODE REVIEW

**Comment by jmark99** [comment]
@DomGarguilo I cloned your PR and went through the step-by-step procedures with no issue. But when running the SampleExample I'm still seeing an exception related to the CompactionStrategy class.

`
$ ./bin/runex sample.SampleExample
Scanning all data :
  2317 doc:context [] 1649437430445 false milk, eggs, bread, parmigiano-reggiano
  2317 doc:url [] 1649437430445 false file://groceries/9/txt
  3900 doc:context [] 1649437430445 false EC2 ate my homework
  3900 doc:url [] 1649437430445 false file://final_project.txt
  8934 doc:context [] 1649437430445 false accumulo scales
  8934 doc:url [] 1649437430445 false file://accumulo_notes.txt
  9225 doc:context [] 1649437430445 false abcde
  9225 doc:url [] 1649437430445 false file://foo.txt

Scanning with sampler configuration.  Data was written before sampler was set on table, scan should fail.
  Saw sample not present exception as expected.

Exception in thread "main" org.apache.accumulo.core.client.AccumuloException: TabletServer could not load CompactionStrategy class org.apache.accumulo.tserver.compaction.strategies.ConfigurableCompactionStrategy
        at org.apache.accumulo.core.clientImpl.TableOperationsImpl.ensureStrategyCanLoad(TableOperationsImpl.java:914)
        at org.apache.accumulo.core.clientImpl.TableOperationsImpl.compact(TableOperationsImpl.java:865)
        at org.apache.accumulo.examples.sample.SampleExample.main(SampleExample.java:107)
`

Did you see the error or do I have something misconfigured?

**Comment by DomGarguilo** [comment]
@jmark99 did you add the accumulo-examples.jar and accumulo-examples-shaded.jar to the `/lib` directory of your Accumulo instance? I've recently run into something similar and that is what was causing the error for me.

**Comment by jmark99** [comment]
@DomGarguilo sorry about the false alarm. Something happened and the SampleExample class was not updated correctly when I ran it. Re-downloaded and successfully ran the example.

**Review by jmark99 — APPROVED** [review]
Successfully ran the example without errors.

File: src/main/java/org/apache/accumulo/examples/sample/SampleExample.java [hunk 1]
```diff
@@ -144,6 +143,7 @@ public static void main(String[] args) throws Exception {
 
       System.out.println("Scanning with new sampler configuration : ");
       print(scanner);
+      scanner.close();
```
Comment (ctubbsii) [inline src/main/java/org/apache/accumulo/examples/sample/SampleExample.java]: This should be in a try-with-resources block instead of an explicit close call.

Comment (DomGarguilo) [reply src/main/java/org/apache/accumulo/examples/sample/SampleExample.java]: Addressed in [b31cf77](https://github.com/apache/accumulo-examples/pull/99/commits/b31cf77b86909f2e6ee239081a749a5dd6c2d0d5)
