### PR TITLE
Removes try-block around client. Fixes #45

### LINKED ISSUE #45: reservations example fails
>reserve room06 20140101 alice bob eve mallory trent

```java
2019-04-18 10:23:09,006 [examples.reservations.ARS] WARN : Could not write to the ConsoleReader.
java.lang.IllegalStateException: This client was closed.
	at org.apache.accumulo.core.clientImpl.ClientContext.ensureOpen(ClientContext.java:114)
	at org.apache.accumulo.core.clientImpl.ClientContext.createConditionalWriter(ClientContext.java:539)
	at org.apache.accumulo.examples.reservations.ARS.reserve(ARS.java:97)
	at org.apache.accumulo.examples.reservations.ARS$1.run(ARS.java:276)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by Manno15**

### CODE REVIEW

**Review by keith-turner — APPROVED** [review]

File: src/main/java/org/apache/accumulo/examples/reservations/ARS.java [hunk 1]
```diff
@@ -301,14 +301,15 @@ public void run() {
...
-            reader.println("  No Such Table");
-        }
+        // its good to close clients when possible, but it was not done here for simplicity
+        AccumuloClient client = Accumulo.newClient().to(tokens[1], tokens[2])
+            .as(tokens[3], tokens[4]).build();
+        if (client.tableOperations().exists(tokens[5])) {
+          ars = new ARS(client, tokens[5]);
+          reader.println("  connected");
+        } else
+          reader.println("  No Such Table");
```
Comment (ctubbsii) [inline src/main/java/org/apache/accumulo/examples/reservations/ARS.java:312]: This is a very confusing nesting without the braces.

File: src/main/java/org/apache/accumulo/examples/reservations/ARS.java [hunk 2]
```diff
@@ -301,14 +301,15 @@ public void run() {
...
       } else if (tokens[0].equals("connect") && tokens.length == 6 && ars == null) {
-        try (AccumuloClient client = Accumulo.newClient().to(tokens[1], tokens[2])
-            .as(tokens[3], tokens[4]).build()) {
-          if (client.tableOperations().exists(tokens[5])) {
-            ars = new ARS(client, tokens[5]);
-            reader.println("  connected");
-          } else
-            reader.println("  No Such Table");
-        }
+        // its good to close clients when possible, but it was not done here for simplicity
```
Comment (ctubbsii) [inline src/main/java/org/apache/accumulo/examples/reservations/ARS.java]: This comment could be improved to explain why the client needs to be left open here. I don't think it's merely a matter of "simplicity".

Comment (keith-turner) [reply src/main/java/org/apache/accumulo/examples/reservations/ARS.java]: > This comment could be improved to explain why the client needs to be left open here.

@ctubbsii what wording would you suggest?

Comment (ctubbsii) [reply src/main/java/org/apache/accumulo/examples/reservations/ARS.java]: Initially, I didn't understand why the client needed to be open here, so I was suggesting an improvement in the comment that would explain that. However, @keith-turner  explained it to me out of band, so now I understand why and can suggest the following:

```suggestion
        // the client can't be closed here, because it is passed to the new ARS object and keeping it open is simpler than adding code to close it later
```

Comment (ctubbsii) [reply src/main/java/org/apache/accumulo/examples/reservations/ARS.java]: Or, more succinctly:

```suggestion
        // the client can't be closed here, because it is passed to the new ARS object
```

Comment (Manno15) [reply src/main/java/org/apache/accumulo/examples/reservations/ARS.java]: Thank you, I will change the comment

File: src/main/java/org/apache/accumulo/examples/reservations/ARS.java (hunk 1 above)
Comment (Manno15) [reply src/main/java/org/apache/accumulo/examples/reservations/ARS.java:312]: The braces around the else? I didn't notice that when I was removing the try-block braces, thanks for bringing it to my attention.
